"""
TypedDict definitions for CFLV Call Reports harmonized records.

All financial fields are Optional[float] — data availability varies by bank,
form type (FFIEC 031/041/051), and year.
All monetary units: thousands of USD.
Income statement fields are year-to-date (YTD) cumulative.
"""
from datetime import date
from typing import Optional, TypedDict


class BalanceSheetRecord(TypedDict, total=False):
    # ── Identifiers ───────────────────────────────────────────────────────────
    id_rssd: int
    date: date
    id_rssd_hd_off: Optional[int]
    id_cusip: Optional[str]
    id_thrift: Optional[str]
    id_aba_prim: Optional[str]
    id_fdic_cert: Optional[int]
    id_occ: Optional[str]
    id_tax: Optional[str]
    id_lei: Optional[str]
    nm_lgl: Optional[str]
    nm_short: Optional[str]
    city: Optional[str]
    state_abbr_nm: Optional[str]
    state_cd: Optional[str]
    zip_cd: Optional[str]
    county_cd: Optional[str]
    cntry_cd: Optional[str]
    cntry_nm: Optional[str]
    dist_frs: Optional[str]
    ent_type_cd: Optional[str]
    entity_type: Optional[str]
    chtr_type_cd: Optional[str]
    act_prim_cd: Optional[str]
    reason_term_cd: Optional[str]
    dt_open: Optional[str]
    reg_hh_1_id: Optional[int]
    fin_hh_id: Optional[int]
    reg_dh_1_id: Optional[int]
    fgn_call_fam_id: Optional[int]
    fgn_call_cntry_cd: Optional[str]
    street_line1: Optional[str]
    # ── Core balance sheet ────────────────────────────────────────────────────
    cash: Optional[float]
    securities: Optional[float]
    ln_tot_gross: Optional[float]
    ln_tot: Optional[float]
    llres: Optional[float]
    trad_ass: Optional[float]
    ffrepo_ass: Optional[float]
    ffsold: Optional[float]
    repo_purch: Optional[float]
    fixed_ass: Optional[float]
    oreo: Optional[float]
    oth_assets: Optional[float]
    oth_assets_alt: Optional[float]
    assets: Optional[float]
    demand_deposits: Optional[float]
    time_deposits: Optional[float]
    deposits: Optional[float]
    ffrepo_liab: Optional[float]
    ffpurch: Optional[float]
    repo_sold: Optional[float]
    trad_liab: Optional[float]
    othbor_liab: Optional[float]
    subdebt: Optional[float]
    liab_oth: Optional[float]
    liab_tot: Optional[float]
    liab_tot_unadj: Optional[float]
    minorint: Optional[float]
    pref_stock: Optional[float]
    comm_stock: Optional[float]
    surplus: Optional[float]
    retain_earn: Optional[float]
    equity: Optional[float]
    # ── Loan categories ───────────────────────────────────────────────────────
    ln_re: Optional[float]
    ln_fi: Optional[float]
    ln_dep_inst: Optional[float]
    ln_dep_inst_dom: Optional[float]
    ln_oth: Optional[float]
    ln_cc: Optional[float]
    ln_ci: Optional[float]
    ln_cons: Optional[float]
    ln_agr: Optional[float]
    ln_lease: Optional[float]
    npl_tot: Optional[float]
    # ── Deposits detail ───────────────────────────────────────────────────────
    brokered_dep: Optional[float]
    brokered_dep_lt100k: Optional[float]
    brokered_dep_ge100k: Optional[float]
    insured_deposits: Optional[float]
    insured_deposits_alt: Optional[float]
    transaction_dep: Optional[float]
    nontransaction_dep: Optional[float]
    nontransaction_sav_dep: Optional[float]
    time_sav_dep: Optional[float]
    tot_sav_dep: Optional[float]
    time_dep_ge100k: Optional[float]
    time_cd_ge100k: Optional[float]
    time_dep_lt100k: Optional[float]
    time_dep_gt250k: Optional[float]
    time_ge100k_le250k: Optional[float]
    time_dep_le250k: Optional[float]
    uninsured_time_dep: Optional[float]
    domestic_dep: Optional[float]
    foreign_dep: Optional[float]
    dom_deposit_ib: Optional[float]
    dom_deposit_nib: Optional[float]
    for_deposit_ib: Optional[float]
    for_deposit_nib: Optional[float]
    # ── Securities detail ─────────────────────────────────────────────────────
    securities_ac: Optional[float]
    htmsec_ac: Optional[float]
    afssec_fv: Optional[float]
    # ── Interest rate sensitivity (maturity buckets) ──────────────────────────
    ust_sec_3mo_less: Optional[float]
    ust_sec_3mo_12mo: Optional[float]
    ust_sec_1y_3y: Optional[float]
    ust_sec_3y_5y: Optional[float]
    ust_sec_5y_15y: Optional[float]
    ust_sec_over_15y: Optional[float]
    res_mbs_3mo_less: Optional[float]
    res_mbs_3mo_12mo: Optional[float]
    res_mbs_1y_3y: Optional[float]
    res_mbs_3y_5y: Optional[float]
    res_mbs_5y_15y: Optional[float]
    res_mbs_over_15y: Optional[float]
    other_mbs_3y_less: Optional[float]
    other_mbs_3y_more: Optional[float]
    securities_3mo_less: Optional[float]
    securities_3mo_12mo: Optional[float]
    securities_1y_3y: Optional[float]
    securities_3y_5y: Optional[float]
    securities_5y_15y: Optional[float]
    securities_over_15y: Optional[float]
    securities_mat_1y_less: Optional[float]
    res_loans_3mo_less: Optional[float]
    res_loans_3mo_12mo: Optional[float]
    res_loans_1y_3y: Optional[float]
    res_loans_3y_5y: Optional[float]
    res_loans_5y_15y: Optional[float]
    res_loans_over_15y: Optional[float]
    ln_lease_3mo_less: Optional[float]
    ln_lease_3mo_12mo: Optional[float]
    ln_lease_1y_3y: Optional[float]
    ln_lease_3y_5y: Optional[float]
    ln_lease_5y_15y: Optional[float]
    ln_lease_over_15y: Optional[float]
    ln_lease_mat_1y_less: Optional[float]
    # Time deposit maturity buckets
    time_dep_lt100k_3mo_less: Optional[float]
    time_dep_lt100k_3mo_12mo: Optional[float]
    time_dep_lt100k_1y_3y: Optional[float]
    time_dep_lt100k_over_3yr: Optional[float]
    time_dep_lt100k_mat_1y_less: Optional[float]
    time_dep_ge100k_3mo_less: Optional[float]
    time_dep_ge100k_3mo_12mo: Optional[float]
    time_dep_ge100k_1y_3y: Optional[float]
    time_dep_ge100k_over_3yr: Optional[float]
    time_dep_le250k_3mo_less: Optional[float]
    time_dep_le250k_3mo_12mo: Optional[float]
    time_dep_le250k_1y_3y: Optional[float]
    time_dep_le250k_over_3yr: Optional[float]
    time_dep_le250k_mat_1y_less: Optional[float]
    time_dep_gt250k_3mo_less: Optional[float]
    time_dep_gt250k_3mo_12mo: Optional[float]
    time_dep_gt250k_1y_3y: Optional[float]
    time_dep_gt250k_over_3yr: Optional[float]
    # ── Quarterly averages ────────────────────────────────────────────────────
    qtr_avg_ib_bal_due: Optional[float]
    qtr_avg_securities: Optional[float]
    qtr_avg_ust_sec: Optional[float]
    qtr_avg_mbs: Optional[float]
    qtr_avg_oth_sec: Optional[float]
    qtr_avg_trad_ass: Optional[float]
    qtr_avg_ffrepo_ass: Optional[float]
    qtr_avg_ln_tot: Optional[float]
    qtr_avg_ln_re: Optional[float]
    qtr_avg_ln_rre: Optional[float]
    qtr_avg_ln_othre: Optional[float]
    qtr_avg_ln_agr: Optional[float]
    qtr_avg_ln_ci: Optional[float]
    qtr_avg_ln_cons: Optional[float]
    qtr_avg_ln_cc: Optional[float]
    qtr_avg_ln_othcons: Optional[float]
    qtr_avg_ln_fgn: Optional[float]
    qtr_avg_lease: Optional[float]
    qtr_avg_assets: Optional[float]
    qtr_avg_trans_dep_dom: Optional[float]
    qtr_avg_sav_dep_dom: Optional[float]
    qtr_avg_time_dep_ge100k: Optional[float]
    qtr_avg_time_dep_gt250k: Optional[float]
    qtr_avg_time_dep_lt100k: Optional[float]
    qtr_avg_time_dep_le250k: Optional[float]
    qtr_avg_time_cd_ge100k: Optional[float]
    qtr_avg_fgn_dep: Optional[float]
    qtr_avg_ffrepo_liab: Optional[float]
    qtr_avg_othbor_liab: Optional[float]
    # ── Derivatives ───────────────────────────────────────────────────────────
    tot_gna_deriv_ir: Optional[float]
    tot_gna_deriv_ir_par: Optional[float]
    gross_hedging: Optional[float]
    tot_gna_ir_fixed_rate_swap: Optional[float]
    tot_swaps_int_rate: Optional[float]
    tot_gna_ir_float_rate_swap: Optional[float]
    net_hedging: Optional[float]
    tot_gna_deriv_trad_ir: Optional[float]


class IncomeStatementRecord(TypedDict, total=False):
    # ── Identifiers ───────────────────────────────────────────────────────────
    id_rssd: int
    date: date
    # ── Interest income (YTD) ─────────────────────────────────────────────────
    ytdint_inc: Optional[float]
    ytdint_inc_sec: Optional[float]
    ytdint_inc_sec_ust: Optional[float]
    ytdint_inc_sec_mbs: Optional[float]
    ytdint_inc_sec_oth: Optional[float]
    ytdint_inc_ln: Optional[float]
    ytdint_inc_ln_re: Optional[float]
    ytdint_inc_ln_rre: Optional[float]
    ytdint_inc_ln_othre: Optional[float]
    ytdint_inc_ln_agr: Optional[float]
    ytdint_inc_ln_ci: Optional[float]
    ytdint_inc_ln_cc: Optional[float]
    ytdint_inc_ln_othcons: Optional[float]
    ytdint_inc_ln_indiv: Optional[float]
    ytdint_inc_ln_fgn: Optional[float]
    ytdint_inc_ffrepo: Optional[float]
    ytdint_inc_lease: Optional[float]
    ytdint_inc_ibb: Optional[float]
    ytdint_inc_net: Optional[float]
    # ── Interest expense (YTD) ────────────────────────────────────────────────
    ytdint_exp: Optional[float]
    ytdint_exp_dep: Optional[float]
    ytdint_exp_ffrepo: Optional[float]
    ytdint_exp_othbor: Optional[float]
    ytdint_exp_trad_othbor: Optional[float]
    ytdint_exp_subdebt: Optional[float]
    ytdint_exp_time_dep: Optional[float]
    ytdint_exp_time_ge100k_dom: Optional[float]
    ytdint_exp_time_lt100k_dom: Optional[float]
    ytdint_exp_time_le250k_dom: Optional[float]
    ytdint_exp_time_gt250k_dom: Optional[float]
    ytdint_exp_trans_dep_dom: Optional[float]
    ytdint_exp_savings_dep_dom: Optional[float]
    ytdint_exp_fgn: Optional[float]
    # ── Noninterest income (YTD) ──────────────────────────────────────────────
    ytdnonint_inc: Optional[float]
    ytdfiduc_inc: Optional[float]
    ytdnonint_inc_srv_chrg_dep: Optional[float]
    ytdoth_srv_chrg: Optional[float]
    ytdoth_operating_inc: Optional[float]
    ytdoth_operating_inc_adj: Optional[float]
    ytdtradrev_inc: Optional[float]
    ytdoperating_inc_tot: Optional[float]
    ytdop_inc_tot_1960: Optional[float]
    # ── Noninterest expense (YTD) ─────────────────────────────────────────────
    ytdnonint_exp: Optional[float]
    ytdnonint_exp_comp: Optional[float]
    ytdnonint_exp_fass: Optional[float]
    ytdoth_operating_exp: Optional[float]
    ytdoperating_exp_tot: Optional[float]
    ytdoperating_exp_tot_adj: Optional[float]
    ytdop_exp_tot_1960: Optional[float]
    # ── Provisions, charge-offs, recoveries (YTD) ─────────────────────────────
    ytdllprov: Optional[float]
    ytdxoff_tot: Optional[float]
    ytdrecov_tot: Optional[float]
    # ── Profitability (YTD) ───────────────────────────────────────────────────
    ytdnet_operating_earn: Optional[float]
    ytdnet_op_earn_1960: Optional[float]
    ytdinc_before_sec_gain: Optional[float]
    ytdinc_before_disc_op: Optional[float]
    ytdsecur_inc: Optional[float]
    ytdsec_net: Optional[float]
    ytdextra_inc_gross: Optional[float]
    ytdextra_inc: Optional[float]
    ytddisc_op: Optional[float]
    ytdminor_int: Optional[float]
    ytdnetinc: Optional[float]
    # ── Taxes (YTD) ──────────────────────────────────────────────────────────
    ytdinc_taxes: Optional[float]
    ytdinc_taxes_net: Optional[float]
    ytdinc_taxes_netsec: Optional[float]
    ytdinc_taxes_sec: Optional[float]
    # ── Other ─────────────────────────────────────────────────────────────────
    ytdcommdividend: Optional[float]
    num_employees: Optional[float]
